#
# close-bad-pr.yml
# Automatically close the PR if it's directed to a release branch
#
# <p>Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches.
#    We make patches to the bugfix branches and only later do we push them out as releases.
#    Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x`
#    when resubmitting the PR. It may help to set your fork's default branch to `bugfix-2.0.x`.</p>
# <p>See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.</p>
#

name: Close PR

on:
  pull_request:
    branches:
    - 1.0.x
    - 1.1.x
    - 2.0.x

jobs:
  close_pr:

    runs-on: ubuntu-latest

    steps:
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: |
          <p>Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches.
          We make patches to the bugfix branches and only later do we push them out as releases.
          Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x`
          when resubmitting the PR. It may help to set your fork's default branch to `bugfix-2.0.x`.</p>
          <p>See http://marlinfw.org/docs/development/getting_started_pull_requests.html for full instructions.</p>
